// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {mod} from '../models';
import {plugin} from '../models';
import {ai} from '../models';
import {cost} from '../models';
import {sshutil} from '../models';
import {time} from '../models';

export function AIChatStream(arg1:string,arg2:string,arg3:Array<main.AIChatMessage>):Promise<void>;

export function AICostOptimization():Promise<void>;

export function AIGenerateTemplate(arg1:string):Promise<void>;

export function AIRecommendTemplates(arg1:string):Promise<void>;

export function AddHTTPServerUser(arg1:string,arg2:string):Promise<mod.HTTPUser>;

export function AgentChatStream(arg1:string,arg2:Array<main.AIChatMessage>):Promise<void>;

export function AnalyzeCaseError(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AnalyzeDeploymentError(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function BatchDeleteCustomDeployments(arg1:Array<string>):Promise<Array<mod.BatchOperationResult>>;

export function BatchStartCustomDeployments(arg1:Array<string>):Promise<Array<mod.BatchOperationResult>>;

export function BatchStopCustomDeployments(arg1:Array<string>):Promise<Array<mod.BatchOperationResult>>;

export function BuildF8xCommand(arg1:Array<string>):Promise<string>;

export function CancelScheduledTask(arg1:string):Promise<void>;

export function CheckAllUpdates():Promise<main.UpdateCheckResult>;

export function CheckForUpdates():Promise<main.VersionCheckResult>;

export function ClearAuditLogs():Promise<void>;

export function ClearTimeline():Promise<void>;

export function CloneCase(arg1:string,arg2:string):Promise<void>;

export function CloneCustomDeployment(arg1:string,arg2:string):Promise<mod.CustomDeployment>;

export function CloseTerminal(arg1:string):Promise<void>;

export function ComposeDown(arg1:string,arg2:Array<string>):Promise<void>;

export function ComposeDownSync(arg1:string,arg2:Array<string>):Promise<void>;

export function ComposePreview(arg1:string,arg2:Array<string>):Promise<main.ComposeSummary>;

export function ComposeUp(arg1:string,arg2:Array<string>):Promise<void>;

export function ComposeUpSync(arg1:string,arg2:Array<string>):Promise<any>;

export function CopyFileTo(arg1:string,arg2:string):Promise<void>;

export function CopyTemplate(arg1:string,arg2:string):Promise<void>;

export function CreateAndRunCase(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function CreateCase(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function CreateCustomDeployment(arg1:mod.DeploymentConfig):Promise<mod.CustomDeployment>;

export function CreateLocalTemplate(arg1:string,arg2:string):Promise<void>;

export function CreateProfile(arg1:string,arg2:string,arg3:string):Promise<mod.ProfileInfo>;

export function CreateProject(arg1:string):Promise<void>;

export function CreateRemoteDirectory(arg1:string,arg2:string):Promise<void>;

export function DeleteConfigTemplate(arg1:string):Promise<void>;

export function DeleteCustomDeployment(arg1:string):Promise<void>;

export function DeleteCustomSkill(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteRemoteFile(arg1:string,arg2:string):Promise<void>;

export function DeleteTemplateFile(arg1:string,arg2:string):Promise<void>;

export function DeployAgentChatStream(arg1:string,arg2:Array<main.AIChatMessage>):Promise<void>;

export function DeployCase(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function DisablePlugin(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<main.FileTransferResult>;

export function EnablePlugin(arg1:string):Promise<void>;

export function EnsureF8x(arg1:string):Promise<main.ExecCommandResult>;

export function EstimateDeploymentCost(arg1:mod.DeploymentConfig):Promise<mod.CostEstimate>;

export function ExecCommand(arg1:string,arg2:string):Promise<main.ExecCommandResult>;

export function ExecUserdata(arg1:string,arg2:string):Promise<main.ExecCommandResult>;

export function ExportAuditLogs():Promise<Array<mod.AuditLogEntry>>;

export function ExportChatLog(arg1:string):Promise<void>;

export function ExportConfigTemplate(arg1:string,arg2:string):Promise<void>;

export function ExportConsoleLogs(arg1:string):Promise<void>;

export function ExportTemplates(arg1:Array<string>):Promise<string>;

export function FetchPluginRegistry():Promise<Array<plugin.RegistryPlugin>>;

export function FetchRegistryTemplates(arg1:string):Promise<Array<main.RegistryTemplate>>;

export function FetchSkillsRegistry():Promise<Array<ai.RegistrySkill>>;

export function FetchTemplateReadme(arg1:string,arg2:string):Promise<string>;

export function GetActiveProfile():Promise<mod.ProfileInfo>;

export function GetAllCaseTags():Promise<Record<string, Array<string>>>;

export function GetAllTagNames():Promise<Array<string>>;

export function GetAuditLogs(arg1:number,arg2:number,arg3:string,arg4:string):Promise<main.AuditLogResult>;

export function GetBalances(arg1:Array<string>):Promise<Array<main.BalanceInfo>>;

export function GetBaseTemplates():Promise<Array<mod.BaseTemplate>>;

export function GetBills(arg1:Array<string>):Promise<Array<main.BillInfo>>;

export function GetCaseOutputs(arg1:string):Promise<Record<string, string>>;

export function GetCasePlanPreview(arg1:string):Promise<main.PlanPreview>;

export function GetConfig():Promise<main.ConfigInfo>;

export function GetCostEstimate(arg1:string,arg2:Record<string, string>):Promise<cost.CostEstimate>;

export function GetCurrentProject():Promise<string>;

export function GetDeploymentHistory(arg1:string):Promise<Array<mod.DeploymentChangeHistory>>;

export function GetDeploymentPlanPreview(arg1:string):Promise<main.PlanPreview>;

export function GetDisableRightClick():Promise<boolean>;

export function GetF8xCatalog():Promise<Array<mod.F8xModule>>;

export function GetF8xCategories():Promise<Array<mod.F8xCategoryInfo>>;

export function GetF8xInstallHistory(arg1:string):Promise<Array<main.F8xInstallRecord>>;

export function GetF8xPresets():Promise<Array<mod.F8xPreset>>;

export function GetF8xRunningTasks():Promise<Array<main.F8xInstallRecord>>;

export function GetF8xStatus(arg1:string):Promise<main.F8xStatus>;

export function GetHTTPServerConfig():Promise<Record<string, any>>;

export function GetHTTPServerStatus():Promise<Record<string, any>>;

export function GetHTTPServerUsers():Promise<Array<mod.HTTPUser>>;

export function GetInstanceTypes(arg1:string,arg2:string):Promise<Array<mod.InstanceType>>;

export function GetLanguage():Promise<string>;

export function GetMCPStatus():Promise<main.MCPStatus>;

export function GetNotificationEnabled():Promise<boolean>;

export function GetOnboardingStatus():Promise<main.OnboardingStatus>;

export function GetPluginConfig(arg1:string):Promise<string>;

export function GetPluginsDir():Promise<string>;

export function GetPredictedMonthlyCost():Promise<string>;

export function GetProfileFallbackProviders(arg1:string):Promise<Array<mod.FallbackProvider>>;

export function GetProviderRegions(arg1:string):Promise<Array<mod.Region>>;

export function GetProvidersConfig(arg1:string):Promise<main.ProvidersConfigInfo>;

export function GetRemoteFileContent(arg1:string,arg2:string):Promise<string>;

export function GetResourceSummary():Promise<Array<main.ResourceSummary>>;

export function GetSSHInfoForCase(arg1:string):Promise<Record<string, any>>;

export function GetSSHInfosForCase(arg1:string):Promise<Array<Record<string, any>>>;

export function GetScheduledTask(arg1:string):Promise<mod.ScheduledTask>;

export function GetShowWelcomeDialog():Promise<boolean>;

export function GetSkill(arg1:string):Promise<ai.Skill>;

export function GetSkillsDir():Promise<string>;

export function GetSpotAutoRecoverEnabled():Promise<boolean>;

export function GetSpotMonitorEnabled():Promise<boolean>;

export function GetTemplateFiles(arg1:string):Promise<Record<string, string>>;

export function GetTemplateMetadata(arg1:string):Promise<mod.BaseTemplate>;

export function GetTemplateVariables(arg1:string):Promise<Array<main.TemplateVariable>>;

export function GetTemplatesDir():Promise<string>;

export function GetTerraformMirrorConfig():Promise<main.TerraformMirrorConfig>;

export function GetTotalRuntime():Promise<string>;

export function GetVersion():Promise<string>;

export function GetWebhookConfig():Promise<main.WebhookConfig>;

export function HasActiveOperations():Promise<boolean>;

export function ImportConfigTemplate(arg1:string,arg2:string):Promise<void>;

export function ImportTemplates(arg1:string):Promise<Array<string>>;

export function InstallAllSkills():Promise<number>;

export function InstallPlugin(arg1:string):Promise<void>;

export function InstallSkill(arg1:string,arg2:string):Promise<void>;

export function ListAllScheduledTasks():Promise<Array<mod.ScheduledTask>>;

export function ListAllTemplates():Promise<Array<main.TemplateInfo>>;

export function ListCaseScheduledTasks(arg1:string):Promise<Array<mod.ScheduledTask>>;

export function ListCases():Promise<Array<main.CaseInfo>>;

export function ListComposeTemplates():Promise<Array<mod.ComposeTemplate>>;

export function ListConfigTemplates():Promise<Array<string>>;

export function ListCustomDeployments():Promise<Array<mod.CustomDeployment>>;

export function ListPlugins():Promise<Array<main.PluginInfo>>;

export function ListPortForwards():Promise<Array<main.PortForwardInfo>>;

export function ListProfiles():Promise<Array<mod.ProfileInfo>>;

export function ListProjects():Promise<Array<main.ProjectInfo>>;

export function ListRemoteFiles(arg1:string,arg2:string):Promise<Array<sshutil.FileInfo>>;

export function ListScheduledTasks():Promise<Array<mod.ScheduledTask>>;

export function ListSkills(arg1:string):Promise<Array<ai.SkillIndex>>;

export function ListTemplates():Promise<Array<main.TemplateInfo>>;

export function ListTimelineEvents(arg1:number,arg2:number,arg3:string,arg4:string):Promise<mod.TimelineListResult>;

export function ListUserdataTemplates():Promise<Array<mod.UserdataTemplate>>;

export function LoadConfigTemplate(arg1:string):Promise<mod.DeploymentConfig>;

export function MCPCancelScheduledTask(arg1:string):Promise<void>;

export function MCPComposeDown(arg1:string,arg2:Array<string>):Promise<void>;

export function MCPComposeDownSync(arg1:string,arg2:Array<string>):Promise<void>;

export function MCPComposePreview(arg1:string,arg2:Array<string>):Promise<any>;

export function MCPComposeUp(arg1:string,arg2:Array<string>):Promise<void>;

export function MCPComposeUpSync(arg1:string,arg2:Array<string>):Promise<any>;

export function MCPGetActiveProfile():Promise<any>;

export function MCPGetBalances(arg1:Array<string>):Promise<any>;

export function MCPGetBills(arg1:Array<string>):Promise<any>;

export function MCPGetCostEstimate(arg1:string,arg2:Record<string, string>):Promise<any>;

export function MCPGetPredictedMonthlyCost():Promise<string>;

export function MCPGetResourceSummary():Promise<any>;

export function MCPGetTotalRuntime():Promise<string>;

export function MCPListCustomDeployments():Promise<any>;

export function MCPListProfiles():Promise<any>;

export function MCPListProjects():Promise<any>;

export function MCPListScheduledTasks():Promise<any>;

export function MCPSaveComposeFile(arg1:string,arg2:string):Promise<string>;

export function MCPSaveTemplateFiles(arg1:string,arg2:Record<string, string>):Promise<string>;

export function MCPScheduleTask(arg1:string,arg2:string,arg3:string,arg4:time.Time):Promise<any>;

export function MCPScheduleTaskFull(arg1:string,arg2:string,arg3:string,arg4:time.Time,arg5:string,arg6:number,arg7:string,arg8:boolean):Promise<any>;

export function MCPSetActiveProfile(arg1:string):Promise<any>;

export function MCPStartCustomDeployment(arg1:string):Promise<void>;

export function MCPStopCustomDeployment(arg1:string):Promise<void>;

export function MCPSwitchProject(arg1:string):Promise<void>;

export function OrchestratorStream(arg1:string,arg2:main.OrchestratorConfig,arg3:Array<main.AIChatMessage>):Promise<void>;

export function PullTemplate(arg1:string,arg2:boolean):Promise<void>;

export function RecommendTemplates(arg1:string):Promise<Array<main.TemplateRecommendation>>;

export function RefreshF8xCatalog():Promise<Record<string, any>>;

export function RemoveCase(arg1:string):Promise<void>;

export function RemoveHTTPServerUser(arg1:string):Promise<void>;

export function RemoveTemplate(arg1:string):Promise<void>;

export function RenameRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RunF8xInstall(arg1:string,arg2:Array<string>):Promise<string>;

export function SaveConfigTemplate(arg1:string,arg2:mod.DeploymentConfig):Promise<void>;

export function SaveCustomSkill(arg1:string,arg2:string):Promise<void>;

export function SavePluginConfig(arg1:string,arg2:string):Promise<void>;

export function SaveProvidersConfig(arg1:string,arg2:Record<string, string>,arg3:string):Promise<void>;

export function SaveProxyConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveTemplateFiles(arg1:string,arg2:Record<string, string>):Promise<string>;

export function SaveTerraformMirrorConfig(arg1:boolean,arg2:Array<string>,arg3:string,arg4:boolean):Promise<void>;

export function ScheduleTask(arg1:string,arg2:string,arg3:string,arg4:time.Time):Promise<mod.ScheduledTask>;

export function ScheduleTaskFull(arg1:string,arg2:string,arg3:string,arg4:time.Time,arg5:string,arg6:number,arg7:string,arg8:boolean):Promise<mod.ScheduledTask>;

export function ScheduleTaskWithRepeat(arg1:string,arg2:string,arg3:string,arg4:time.Time,arg5:string,arg6:number):Promise<mod.ScheduledTask>;

export function SelectComposeFile():Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string):Promise<string>;

export function SetActiveProfile(arg1:string):Promise<mod.ProfileInfo>;

export function SetCaseTags(arg1:string,arg2:Array<string>):Promise<void>;

export function SetDebugLogging(arg1:boolean):Promise<void>;

export function SetDisableRightClick(arg1:boolean):Promise<void>;

export function SetHTTPServerConfig(arg1:boolean,arg2:number,arg3:string,arg4:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetNotificationEnabled(arg1:boolean):Promise<void>;

export function SetOnboardingDismissed():Promise<void>;

export function SetShowWelcomeDialog(arg1:boolean):Promise<void>;

export function SetSpotAutoRecoverEnabled(arg1:boolean):Promise<void>;

export function SetSpotMonitorEnabled(arg1:boolean):Promise<void>;

export function SetWebhookConfig(arg1:main.WebhookConfig):Promise<void>;

export function SmartAgentChatStream(arg1:string,arg2:Array<main.AIChatMessage>):Promise<void>;

export function StartCase(arg1:string):Promise<void>;

export function StartCustomDeployment(arg1:string):Promise<void>;

export function StartHTTPServer(arg1:number,arg2:string,arg3:string):Promise<void>;

export function StartMCPServer(arg1:string,arg2:string):Promise<void>;

export function StartPortForward(arg1:string,arg2:number,arg3:string,arg4:number):Promise<main.PortForwardInfo>;

export function StartSSHTerminal(arg1:string,arg2:number,arg3:number):Promise<string>;

export function StartSSHTerminalDirect(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number):Promise<string>;

export function StartSSHTerminalInstance(arg1:string,arg2:number,arg3:number,arg4:number):Promise<string>;

export function StopAgentStream(arg1:string):Promise<void>;

export function StopCase(arg1:string):Promise<void>;

export function StopCustomDeployment(arg1:string):Promise<void>;

export function StopHTTPServer():Promise<void>;

export function StopMCPServer():Promise<void>;

export function StopPortForward(arg1:string):Promise<void>;

export function SubmitAskUserResponse(arg1:string,arg2:string):Promise<void>;

export function SwitchProject(arg1:string):Promise<void>;

export function TestTerraformEndpoints():Promise<Array<main.EndpointCheck>>;

export function TestWebhook(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TroubleshootAgentChatStream(arg1:string,arg2:Array<main.AIChatMessage>):Promise<void>;

export function UninstallPlugin(arg1:string):Promise<void>;

export function UpdateAllSkills():Promise<number>;

export function UpdateHTTPServerUser(arg1:string,arg2:string,arg3:boolean):Promise<mod.HTTPUser>;

export function UpdatePlugin(arg1:string):Promise<void>;

export function UpdateProfile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<mod.ProfileInfo>;

export function UpdateProfileAIConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:boolean,arg8:number):Promise<void>;

export function UpdateProfileFallbackProviders(arg1:string,arg2:Array<mod.FallbackProvider>):Promise<void>;

export function UpdateSkill(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<main.FileTransferResult>;

export function UploadUserdataScript(arg1:string,arg2:string,arg3:string):Promise<main.FileTransferResult>;

export function ValidateDeploymentConfig(arg1:mod.DeploymentConfig):Promise<mod.ValidationResult>;

export function ValidateTemplate(arg1:string):Promise<main.TemplateValidateResult>;

export function WriteRemoteFileContent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
